/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#9d431b',
        'on-primary': '#ffffff',
        'primary-container': '#e87c4f',
        'on-primary-container': '#5c1d00',
        'inverse-primary': '#ffb599',
        'primary-fixed': '#ffdbce',
        'primary-fixed-dim': '#ffb599',
        'on-primary-fixed': '#370e00',
        'on-primary-fixed-variant': '#7d2c04',

        'secondary': '#1a686c',
        'on-secondary': '#ffffff',
        'secondary-container': '#a8eff3',
        'on-secondary-container': '#236e72',
        'secondary-fixed': '#a8eff3',
        'secondary-fixed-dim': '#8cd2d6',
        'on-secondary-fixed': '#002021',
        'on-secondary-fixed-variant': '#004f53',

        'tertiary': '#75584d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b49286',
        'on-tertiary-container': '#432c23',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#e4beb2',
        'on-tertiary-fixed': '#2b160f',
        'on-tertiary-fixed-variant': '#5b4137',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'surface': '#fbf9f8',
        'on-surface': '#1b1c1c',
        'surface-variant': '#e4e2e2',
        'on-surface-variant': '#56423b',
        'surface-dim': '#dbd9d9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',

        'outline': '#89726a',
        'outline-variant': '#dcc1b7',

        'background': '#fbf9f8',
        'on-background': '#1b1c1c',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        'surface-tint': '#9d431b',

        'warm-bg': '#FDF9F3',
        'success-green': '#2D6A4F',
        'alert-gold': '#C68B16',
        'terracotta-clay': '#B35A38',
      },
      fontFamily: {
        'headline-lg': ['Be Vietnam Pro', 'sans-serif'],
        'headline-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'button-text': ['Work Sans', 'sans-serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'button-text': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'touch-target-min': '48px',
        'gutter': '16px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'stack-sm': '12px',
        'stack-md': '24px',
      },
    },
  },
  plugins: [],
}
